ALTER TABLE book ADD COLUMN deleted BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE author ADD COLUMN deleted BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE country ADD COLUMN deleted BOOLEAN DEFAULT FALSE NOT NULL;