CREATE TABLE activity_log
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    book_name  VARCHAR(255),
    event_time TIMESTAMP WITHOUT TIME ZONE,
    event_type VARCHAR(255),
    CONSTRAINT pk_activitylog PRIMARY KEY (id)
);

CREATE view book_view as
select b.id, b.name, b.category, b.state, b.available_copies,
       a.name || ' ' || a.surname as author_full_name,
       c.name as country_name
from book b
join author a on b.author_id = a.id
join country c on a.country_id = c.id;


CREATE materialized view category_statistics_mview as
select category,
       count(id) as total_books,
       sum(available_copies) as total_available_copies,
       sum(case when state = 'BAD' then 1 else 0 end ) as books_in_bad_state
from book
group by category;