CREATE TABLE library_users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    name     VARCHAR(255),
    surname  VARCHAR(255),
    role     VARCHAR(255),
    CONSTRAINT pk_library_users PRIMARY KEY (id)
);

ALTER TABLE library_users
    ADD CONSTRAINT uc_library_users_username UNIQUE (username);

insert into library_users (username, password, name, surname, role)
values ('admin', 'admin', 'admin', 'admin', 'ROLE_ADMIN');